<?php

return [
    'podłokietnik' => ['armlehne', 'armrest'],
    'błotnik' => ['kotflügel', 'fender', 'wing'],
    'błotnik przedni' => ['kotflügel vorne', 'front fender', 'front wing'],
    'błotnik tylny' => ['kotflügel hinten', 'rear fender', 'rear wing'],
    'reflektor' => ['scheinwerfer', 'headlight'],
    'lampa tylna' => ['rücklicht', 'heckleuchte', 'tail light'],
    'zderzak przedni' => ['stoßstange vorne', 'front bumper'],
    'zderzak tylny' => ['stoßstange hinten', 'rear bumper'],
    'drzwi przednie lewe' => ['tür vorne links', 'front left door'],
    'drzwi przednie prawe' => ['tür vorne rechts', 'front right door'],
    'drzwi tylne lewe' => ['tür hinten links', 'rear left door'],
    'drzwi tylne prawe' => ['tür hinten rechts', 'rear right door'],
    'maska' => ['motorhaube', 'bonnet', 'hood'],
    'klapa tylna' => ['heckklappe', 'tailgate'],
    'lusterko' => ['außenspiegel', 'spiegel', 'mirror'],
    'alternator' => ['lichtmaschine', 'alternator'],
    'rozrusznik' => ['anlasser', 'starter'],
    'turbosprężarka' => ['turbolader', 'turbocharger'],
    'skrzynia biegów' => ['getriebe', 'gearbox', 'transmission'],
    'silnik' => ['motor', 'engine'],
    'pompa ABS' => ['abs pumpe', 'abs pump'],
    'sterownik silnika' => ['motorsteuergerät', 'ecu', 'engine control unit'],
    'licznik' => ['tacho', 'kombiinstrument', 'speedometer'],
    'radio' => ['radio', 'autoradio'],
    'nawigacja' => ['navigation', 'navi'],
    'felga' => ['felge', 'rim', 'wheel'],
    'opona' => ['reifen', 'tyre', 'tire'],
    'piasta' => ['radnabe', 'wheel hub'],
    'zacisk hamulcowy' => ['bremssattel', 'brake caliper'],
];
